### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by gryzli133** [4ib3r/MyTransportPJON#1]
Nice project! Did you test that protocol by yourself for longer period of time for now? I'm looking for an alternative to RS485 that is more stable

**Comment by gioblu** [comment]
Ciao @gryzli133 MyTransportPJON is a MySensors transport based on [PJON](https://github.com/gioblu/PJON). 

The protocol has been in development and testing since years now and many users have implemented operational home automation setups. I think the oldest operational setup is the one of @fredilarsen. 

Consider that the protocol is able to operate using many different wireless or wired physical layers, as well as RS485. Consider also that this codebase (MyTransportPJON) is now obsolete and may not be compatible with the newer versions of PJON, although few changes could make this repo back alive.

@4ib3r are you still willing to maintain this repo?

**Comment by gryzli133** [comment]
@gioblu do you have any description how the protocol is communicating, how the sender is looking for reciver etc? I did some test, some works fine, some seems to have some problem, mostly, when the CPU is blocked by some other operations, f.e. preparing the content for the OLED display. I'm not very good in coding, more copy/paste specialist ;-) This is why it would be better for me to see some block diagram or any test explanation of the operation in software bit bang.

**Comment by gioblu** [comment]
@gryzli133 if a system is busy for a long timeframe doing other things, some packets can be potentially lost unheard, this potentially provoke retransmissions and a loss of bandiwth although the packet is eventually delivered thanks to up to 20 retries in about 3.5 seconds, being SoftwareBitBang based on polling, dedicating a longer timeframe to reception `receive(polling time in microseconds)` the problem can be solved.
- PJON spec: https://github.com/gioblu/PJON/tree/master/specification
- PJDL (SoftwareBitBang physical layer) spec: https://github.com/gioblu/PJON/blob/master/src/strategies/SoftwareBitBang/specification/PJDL-specification-v2.0.md
- SoftwareBitBang README: https://github.com/gioblu/PJON/tree/master/src/strategies/SoftwareBitBang

**Comment by 4ib3r** [comment]
I have been using MySensors with PJON transport for about 2 years and it works perfectly in my home.
